language: ruby
rvm:
- 2.2.2
before_script: gem install jekyll
script: bundle exec jekyll build --destination out
notifications:
  flowdock:
    secure: "U7kKRnsakezQDsHWlmKHGvvY4JfbEXTuwIlFwPOR908zM6mc0V6klgxKsg21J6g9CRruljQb+5fAxSdiDcJxA90td1FhsRnR6qXinG4vWlQpiQ0XpnB27QZ2/XXtCAnrCRTy2gL24o5wIZIQt0/0+B825eIT6ffMElldjVrzfYaiFRWbPPkoQiuNraB8yDRxrtvvboZUvPfEnUCA9GC9FmAyiL9MCCqfbRY5D7SDEGj/bLNmCMZ6Y9tR/qzqd5KknWFk4qt6tPNnrmcSoupi35BUexFwEq46NUMtI4heQKidGZdn8SaqZ8vllvAByqn/QHQtpShOlO5ZPNtI2EpaTdPLRCiR7cJtgNooUwql4ns61NIfoX62jJN8Mh8toIaQqrsU2rj9BSoBRDO9W6JxDy4Ej17eD9ILDlnNCluGAjIHmC5B8vef+8FUYF1nelKC8KHwxbQzf56u1r3NHQUuS3+s9HFWUWg79jSRl7sh+1IA3l1YkSrY/7SAHvzvwm/SpwZzpvF19qmwLDMUhmypa8dzN/7sW6auAhQBlso+7V4nYTaxdlI+ENt4yDZD1aHjlef5LCVjs4rN5HZezyyGdaFH7lDRNm5qiRdmxctn32oGQZhyDm/vQo1yvp9ZkMOmaNOoCv1e49Z6EjQ0h8lpUZdeIq9kop7AvOmB1j0RtSY="
deploy:
  provider: s3
  bucket: home.iyield.co
  skip_cleanup: true
  local-dir: out
  edge: true
  region: eu-west-1
  endpoint: s3-eu-west-1.amazonaws.com
  on:
    branch: master
  access_key_id:
    secure: "q2Nj11HH206jDeUzBfgz0Yb6FVWIXbSsjsm+wF9Pa6O+0mhJNOFPnI++22d7UJwX3+UNJUeGDWcS3zrs+yRZHAQtxCucCnCO6FxLQdrh/Oc07LPIvq7+h6TDpUuEBACzUr2igbJc+lkogff1g8R9umfriBcOouBUQO1vp/y2vYr/DN1ovmg/OZhaz0MVLiKLW+Z1smE6Fm8hDO7fSnuuiCMPChGxcoOnPWoQfIP+BpMiePDvtqdCKUnHxhjsIE+VSyfTGOuBJFdtZ4kAdjyql/8RFqDKgerIjM0hdqXGIlUR08WlmQT4glxmDDMdLXxrOz1+RnGVFboKBxCsQRfvasXFs5iMXO8vO99ggpjU5KRkqFy1UfMevD4spAxH4RHKZtxSr5EjjgRSIHCvmIMQ+udvDwT9hf/ZTi0dQ/8/8K1PzIPfJPfCZlzUwRRWBB3O8c0ZtZOoGzrqY+wA8DAVmRSaHUCLRPQqhBdwASylnWaJeuexBv3cr+hbrQYCPxnr8eqlhEBV2OSEaSKTdQTxtNgWuI9VzRJdoi6AIiYhonA3VB42CsOcmIowoWcdcLRrijbs0PBBgHYq82EaelafwgLzzoNZPKcCTYwpzwHYwy5xMy2a+EgHKm59ougQQd/EgBjMeyyQzyoZt9rGmpqtxVP96wYvNjxqAa3rdF4JOgk="
  secret_access_key:
    secure: "I4UZ0oMPCY57grQ4/XW+u/joOedo8/9RGAYROzv7eeAMAIsPmjoO3TBmxQ9ZZkjisuXgv5Mq6weYQ61hFYv/8uaqvjxW4UqjuC4R0/s3nhK5aaF9oPqAoMGwvxwkmdWbym+csEMsrnFTDhBpq97hLoMvBXA60Y/Ux3fXGarznYsN2l22M/Iw8D1WDveop+nGpElvvD29BZlwE9IBIDAukR53yFQnn9Q5430Qr5pCmXqQmk5mk6L3iA7WRL8w8Ryl1snA2W32Fc+jWeI+fXMUr8Jq/jNlPmNa9qVwMMsyAdGqvrEhSVQARQi7niQmsWZUCtUNoJJ4/gdq+Qm+ZNj23XX/JzEGupzgLDH5ycnOuMyyJgAn9xXag5S6M7HSmu3j6HSA0wsAvmiNMlO3d9MqIMHqzoCHykGQMcian9blf8yhC4aSKdxau1fZFm2R1uiFQneKcV8CRrRv8c4cPzI3Bqdkr86KIhPCdYQpf5lKL11sN/wMle1rX3vyskfU5t830H5e4V0PK7n1XOuJT7UE2YkNg0ZQxxmeXgYgUoBI6uaqKGY0LGkD1msnKgFeh3LZf/7ruZIVst7FBpQUugUEbsMMB8HXNz/1TfG2MHGbvsUBxbvTf76HUTgTbeJX4ylE6WRX8v8tcKwEsQFHYSi24bZ0Al5XaZEHN5uIZjGw7TI="
